# Borrowed from https://github.com/openstreetmap/openstreetmap-website/blob/master/docker-compose.yml
version: "3"

services:

  web:
    # image: osm-edit-app_web:latest
    build:
      context: osm-custom/
    volumes:
      # - ./osm-rails-port/:/app
      # Prevent these directories from mounting so they're not shared between host OS and Docker
      # - /app/node_modules/
      # - /app/tmp/
      # Mount these upload directories so they persist between runs
      - web-traces:/home/osm/traces
      - web-images:/home/osm/images
    ports:
      - "3000:3000"
    environment:
      # Vars for the init script
      PGDATABASE: openstreetmap
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: db
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - db

  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_HOST_AUTH_METHOD: trust
      # POSTGRES_DB: openstreetmap
    volumes:
      # Mount the Postgres data directory so it persists between runs
      - db-data:/var/lib/postgresql/data
  
volumes:
  web-traces:
  web-images:
  db-data: